all:
  hosts:
    xr1_cli:
      ansible_host: 10.62.189.43
      ansible_user: ansible
      ansible_password: ansible
      ansible_connection: ansible.netcommon.network_cli
      ansible_network_os: cisco.iosxr.iosxr

    xr1_netconf:
      ansible_host: 10.62.189.43
      ansible_user: ansible
      ansible_password: ansible
      ansible_connection: ansible.netcommon.netconf
      ansible_network_os: cisco.iosxr.iosxr
